### ISSUE TITLE
Should non-trivial irreps support bias or not?

### ISSUE THREAD

**Issue by prclibo** [QUVA-Lab/e2cnn#13]
Hi @Gabri95 ,

I noticed the current implementation only supports bias for trivial representation as commented:
https://github.com/QUVA-Lab/e2cnn/blob/2604f67fe302e8f88ff089a13562077d73c803f8/e2cnn/nn/modules/r2_conv/r2convolution.py#L184-L189

From a naive intuition, I feel that bias acted on the norm of an irrep seems also equivariant. I didn't find relevant description in the paper. So just a short question for any relevant reference to deny this intuition. Thanks!

**Comment by Gabri95** [comment]
Hi @prclibo 

Thanks for your question!

indeed, the bias can only be added to the trivial representations.
One can show that adding a bias to any other irreducible representation would break equivariance.

However, what you suggest is not the usual notion of bias.
Usually, a linear/conv layer performs an affine transformation, while the bias applied to the norm is a non-linear operation.
For this reason, we chose to not include it in the convolution layer.
As we only needed this kind of bias in the implementation of HNet with norm-nonlinearities we chose to add this bias directly in the implementation of the non-linearity, see https://quva-lab.github.io/e2cnn/api/e2cnn.nn.html#e2cnn.nn.NormNonLinearity

If you need to this kind of bias outside the non-linearity, I can add it as a separate module

Gabriele

**Comment by prclibo** [comment]
Hi @Gabri95 

Thanks for the reply! This explanation makes sense to me. It is fine to use nonlinearity instead.

Bo
