### ISSUE TITLE
Init of Field Dropout

### ISSUE THREAD

**Issue by fabibo3** [QUVA-Lab/e2cnn#14]
When creating a FieldDropout Layer, I get the following error: TypeError: cannot assign 'torch.LongTensor' object to parameter 'indices_8' (torch.nn.Parameter or None required). Initializing PointwiseDropout with the same parameters works.

Is this a known issue?

**Comment by Gabri95** [comment]
Hi @fabibo3,

that is indeed a bug. I mistakenly registered tensor as a parameter instead of a buffer. 
I am sorry for that, but it will push a fixed version of the code in a moment.

Thank you very much for reporting this!

Best,
Gabriele

**Comment by fabibo3** [comment]
Alright, thanks a lot!
