### ISSUE TITLE
pip install error with the legacy_py3.6 branch

### ISSUE THREAD

**Issue by kaikai581** [QUVA-Lab/e2cnn#15]
Hi developers,

I have set up a python environment with python 3.6.9.

When I install the package,
`pip install .`

I encounter the following error
`    ERROR: Command errored out with exit status 1:
     command: /home/kaikai/anaconda3/envs/python3.6.9/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-nx2wsig7/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-nx2wsig7/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-iki7taiq
         cwd: /tmp/pip-req-build-nx2wsig7/
    Complete output (2 lines):
    running egg_info
    error: Invalid distribution name or version syntax: e2cnn-py3.6--0.1
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

It turns out that parentheses are invalid characters in the "name" of setuptools.

I have verified if I change the line in `e2cnn/__about__.py`
from
`__title__ = "e2cnn (py3.6)"`
to
`__title__ = "e2cnn-py3.6"`,
the installation will work.

Would you help take a look at this?

**Comment by Gabri95** [comment]
Hi @kaikai581 

Thanks for reporting this issue. I've fixed it as you suggested and verified that `pip install .` now works.
Let me know if you find other problems

Thanks again!

Gabriele
