### ISSUE TITLE
Why the judgement is the padding_mode != "zeros" rather than == "zeros"?

### ISSUE THREAD

**Issue by yokinglou** [QUVA-Lab/e2cnn#21]
https://github.com/QUVA-Lab/e2cnn/blob/48f49760766ec958b52d0dd7b02483886dfa2096/e2cnn/nn/modules/r2_conv/r2convolution.py#L329

**Comment by Gabri95** [comment]
Hi @yokinglou 

Sorry for this. That is a bug which has already been fixed through a pull request this week.
I'm about to merge it now. Will be solved soon.

Thanks,
Gabriele
