### ISSUE TITLE
PointwiseMaxPoolAntialiased wrongly inherits .export() from parent class.

### ISSUE THREAD

**Issue by drewm1980** [QUVA-Lab/e2cnn#30]
While auditing e2cnn too see if the functions I need actually support .export(), I noticed that:

PointwiseMaxPoolAntialiased:

https://github.com/QUVA-Lab/e2cnn/blob/9054d1ecc7539e981ee06cba0117a09ad3b8f9a9/e2cnn/nn/modules/pooling/pointwise_max.py#L143

inherits the .export() function from PointwiseMaxPool, whereas it should be exporting ops for the antialiased version.

**Comment by drewm1980** [comment]
Closing because it appears this was already "fixed" on master. i.e. it now errors out instead of doing the wrong thing.

**Comment by drewm1980** [comment]
I'm preparing a MR for this.

**Comment by Gabri95** [comment]
Thanks again for reporting and fixing this! :)

Gabriele
