### ISSUE TITLE
concatenation operation

### ISSUE THREAD

**Issue by Tarnekar** [QUVA-Lab/e2cnn#33]
Hello, I am looking for something equivalent to torch.cat, but takes GeometricTensors as inputs and outputs another GeometricTensor. I am developing a rotation-equivariant version of U-net and I need something equivalent to torch.cat for the skip connections. I haven't been able to find something inside the E2CNN library yet that seems to do this.

Thanks again for a really nice framework, I credited it in a recent publication.

**Comment by Gabri95** [comment]
Hi @Tarnekar 

I am happy to hear this :) thanks a lot!

I think this is what you are looking for: https://quva-lab.github.io/e2cnn/api/e2cnn.nn.html#direct-sum

Does this solve your problem?

Best,
Gabriele

**Comment by Tarnekar** [comment]
I believe it does! Thanks!
