### ISSUE TITLE
SequentialModule instead of Sequential

### ISSUE THREAD

**Issue by vitusbenson** [QUVA-Lab/e2cnn#4]
The doc states usage as "e2cnn.nn.Sequential(...)", but it should be "e2cnn.nn.SequentialModule(...)"
https://github.com/QUVA-Lab/e2cnn/blob/30c5ff7c5a53918e01d4e81416127c785a0dcd08/e2cnn/nn/modules/sequential_module.py#L30

**Comment by Gabri95** [comment]
Hi @vitusbenson 

you are right! Thank you very much for reporting it, I will fix it!
