### ISSUE TITLE
A question about cuda acceleration

### ISSUE THREAD

**Issue by kuazhangxiaoai** [QUVA-Lab/e2cnn#43]
Is this package accelerated by cuda?

**Comment by ejnnr** [comment]
The `nn` subpackage uses Pytorch internally for everything, so it supports CUDA acceleration. You can move `GeometricTensor`s to GPU with [`GeometricTensor.to`](https://quva-lab.github.io/e2cnn/api/e2cnn.nn.html#e2cnn.nn.GeometricTensor.to). `EquivariantModule`s are just Pytorch `Module`s so they can also be moved to GPU with `.to(device)`.

The other subpackages use `numpy` and are therefore not CUDA accelerated (also see
https://github.com/QUVA-Lab/e2cnn/issues/39#issuecomment-832546489). But that part of the code is only run once when you initialize your network. So all of the training and inference can be done on GPU.

**Comment by Gabri95** [comment]
Hi @kgavrilyuk 

Thanks @ejnnr  for the faster reply :) 
Indeed, CUDA is supported in the `nn` subpackage, so once you have built your neural network, you should be able to use CUDA acceleration as you usually do in PyTorch

Best,
Gabriele
