### ISSUE TITLE
Need equivariant ResNet & VGG like architectural networks implemented in E2CNN library

### ISSUE THREAD

**Issue by mkool67** [QUVA-Lab/e2cnn#45]
Thank you for this great library for equivariant steerable CNNs. However, I am not able to build an equivariant model for my project through the examples given in this repository. Can you include examples for ResNet & VGG like architectures or can someone tell me how to induce equivariance in these steerable networks. For example, I tried building equivariant model based on WideResNet example given in the repository but I am struggling to induce equivariance and getting only invariance through that.

**Comment by namankhetan** [comment]
Hii @mkool67 I think you haven't included the group pooling layer after the sterrable CNN's block which is required to get the equivariant output from the network as they have mentioned in their paper.

**Comment by mkool67** [comment]
Thank you @namankhetan for pointing this out. I can't see the group pooling layer in the example code. Can you include the code for ResNet & VGG like architectures with groop pooling layer.

**Comment by mkool67** [comment]
Thank you @namankhetan for pointing this out. I looked the example code again and I can't see the group pooling layer in the example code. So, it will be difficult for me to build equivariant model. Can you include code for ResNet & VGG like architectures with groop pooling layer.

**Comment by namankhetan** [comment]
@mkool67 Sure!..will add them in examples folder of the repository. I will also include test cases for you to have a better understanding.

**Comment by namankhetan** [comment]
hey @mkool67 link to the pull request  #46 , let me know any further concers, if any.

**Comment by mkool67** [comment]
Thank you @namankhetan, It worked for me. It is exactly what I was looking for.
