### ISSUE TITLE
Need a size parameter for e2cnn.R2Upsampling Class

### ISSUE THREAD

**Issue by Coronal-Halo** [QUVA-Lab/e2cnn#57]
Currently the e2cnn.R2Upsampling class only has four parameters: in_type, scale_factor, mode and align_corners. However, I think it would be helpful to add another "size" parameter, to be passed to the torch.nn.functional.interpolate method used inside the R2Upsampling class. Sometimes we need to up-sample the input to a specific dimension, especially when dealing with even and odd dimension issues

**Comment by Gabri95** [comment]
Hi @Coronal-Halo 

Sorry for the late reply.
I am trying to gradually move to the new version of the library [escnn](https://github.com/QUVA-Lab/escnn).
Please, take a look at it!

Someone else requested this feature and I will soon integrate it via this [pull request](https://github.com/QUVA-Lab/escnn/pull/5).

I will include this feature here too for the moment, but I am not generally planning to support many more features on this library, so I would recommend the users to move to the new one

Best,
Gabriele
