### ISSUE TITLE
about to set special  rotation equivariant

### ISSUE THREAD

**Issue by Newgaolujie** [QUVA-Lab/e2cnn#62]
Thanks for your work!
According to my understanding,when i set r2_act = gspaces.Rot2dOnR2(N=8) ,it means that when the image is rotated by a 8 specific angle like ↑↗→↘↓↙←↖, the E2CNN outputs the same feature map ,in a similar fashion when N=4 ,the image is rotated by a 4 specific angle like ↑→↓←, the E2CNN outputs the same feature map.
I think it is possible to achieve the  ←↖↑↗→ equivariant,but I'm not familiar with the source code. could you give me some hints?

**Comment by Gabri95** [comment]
Hi @Newgaolujie 

Unfortunately, what you describe is not a group and, therefore, can not be achieved with our library (at least, not in a straightforward way).
As far as I know, this kind of problem has been approached by a few works in the literature, e.g. [this paper](https://arxiv.org/abs/2110.10211). Maybe this can be a good starting point?

Best,
Gabriele

**Comment by Newgaolujie** [comment]
Thank you for your great help~
