### ISSUE TITLE
Difference between trivial output type and regular output type with group pooling

### ISSUE THREAD

**Issue by SpikeRXWong** [QUVA-Lab/e2cnn#73]
Hello, I have a question about the trivial output and regular output followed by group pooling?

**Comment by Gabri95** [comment]
hi @SpikeRXWong 

I am not sure I fully understand your question.

Typically, one uses GroupPooling to turn a feature with regular type into a feature with trivial type.
What do you mean by "trivial output type with group pooling" ?

By the way, note that this is an older version of the library. I'd recommend you to move to the new [escnn](https://github.com/QUVA-Lab/escnn) library which extends `e2cnn` and which I am more actively maintaining.

Best,
Gabriele
