### ISSUE TITLE
Feature Request: Code for generating equivariance visualizations

### ISSUE THREAD

**Issue by drewm1980** [QUVA-Lab/e2cnn#9]
I really like your visualizations of rotation equivariance (i.e. vectorfield.gif and conventional_cnn.gif
), and would like to generate similar ones for my network. Is the code for generating those something that could be easily added, or should I go ahead write my own code for that?

**Comment by swtietz** [comment]
Hey Drew, 

I wrote a little snippet to reproduce the gifs because I thought they were really cool. It was pretty straight forward creating matplotlib plots of rotated activations as shown in introduction.ipynb notebook and then use cv2 VideoWriter to create the video.
Let me know if you need help, I can compile my code into a little notebook for demonstration if there's general interest.

Best,
Stephan

**Comment by drewm1980** [comment]
Hi Stephan,

Thanks for the offer; I'm capable of implementing this; I'm just being a "lazy programmer" and avoiding writing code if it's already been written. If I roll my own I'd try to avoid extra dependencies... generate the frames in pytorch, plus maybe one dependency for creating the video file if torch didn't already take a dependency on any video or animated gif/png writers.

**Comment by Gabri95** [comment]
Hi @drewm1980  and @swtietz 

sorry again for the late replies.

I'm happy you liked our animations :)

I still have that code, though it's not really clean at the moment (it contains a lot of useless code now).
I can clean it and add it in the next couple of days if you still need it.
It only used `matplotlib.animation` to produce the videos but then I cropped and converted them using `ffmpeg`.

Best,
Gabriele

**Comment by Gabri95** [comment]
You can now find my code here:
https://github.com/QUVA-Lab/e2cnn/blob/master/visualizations/animation.py

It's not necessarily the most flexible code for any purpose. 
@swtietz, please, feel free to share your code if you still want to!
Unfortunately, we currently do not have a policy for contributions yet. I will see if we can define one in the meantime.

Thanks for opening this issue! 
I will let it open for a bit in case you want to give some feedback on the visualization code

Best,
Gabriele

**Comment by swtietz** [comment]
@Gabri95 I think your file contains all that is required for now, thanks for sharing!

**Comment by drewm1980** [comment]
@Gabri95 thanks for posting your script! It's going to need some efficiency work to work in my case, but I think it will still be faster to tweak it than starting from scratch.

If you're curious, so far...
First attempt crashed because the code assumes cuda availability.

Tweaked that, and got OOM killed at 60GB RAM usage before it was even done rotating the input images, since it increases the image size 4x4 = 16 times, keeps 72 of them in RAM to process in a batch...

I'm also expecting to have to tweak things later in the code because my model has output that is smaller than the input.

**Comment by Gabri95** [comment]
Hi @drewm1980 

yeah, to generate nicer visualizations it is useful to reduce the aliasing effects produced when you rotate the image.
I've found that rotating the image at the same resolution can introduce a lot of noise in the image (maybe not really visible, but detectable from the network).
To test equivariance numerically, it is better to rotate images at higher resolution and then downsample them.
When using small images, as no high resolution version is available, I usually upsample them, rotate them and finally downsample again. This also seems to help.

Yeah, unfortunately the visualisation code is not super optimized. I never used it for very big networks
